########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS = [
        'EditorPlugin'
    ]

def build(bld):

    bld.DefineGem(
        includes    = ['.',
                       bld.Path('Code/CryEngine/CryCommon')],
        file_list   = ['Substance.waf_files'],
        disable_pch = True,
        win_features        = ['crcfix'],

        # Platform independent defines
        defines = [
            'AIR_NO_DEFAULT_ALLOCATOR',
            'SUBSTANCE_PLATFORM_BLEND'
        ],

        uselib = ['SUBSTANCE'],

        # Platform Roots
        platform_roots = [bld.PlatformRoot('Source/Platform', export_includes=False)],
        
        #==============================
        # WINDOWS
        #==============================
        win_defines = [ 'AZ_USE_SUBSTANCE', 'AIR_USE_WIN32_SYNC=1', 'AIR_NO_DEFAULT_ENGINE' ],
        
        #==============================
        # MACOS
        #==============================
        darwin_defines = ['AZ_USE_SUBSTANCE', 'AIR_USE_PTHREAD_SYNC=1', 'AIR_NO_DEFAULT_ENGINE' ],
        
        # Darwin has linker errors when only declaring libs in the json.
        darwin_lib = [
            'substance_framework',
            'substance_linker',
            'tinyxml',
            'algcompression',
            'pfxlinkercommon'
        ],

        darwin_debug_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/debug')],
        darwin_debug_test_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/debug')],
        darwin_profile_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/release')],
        darwin_profile_test_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/release')],
        darwin_performance_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/release')],
        darwin_release_libpath = [bld.Path('Gems/Substance/External/6.0.0/lib/mac/release')],

        # Copy the potentially runtime loaded pre-compiled Substance dylibs to Bin64Mac
        darwin_copy_dependent_files = ['Gems/Substance/External/6.0.0/bin/mac/release/libsubstance_sse2_blend.1.dylib', 'Gems/Substance/External/6.0.0/bin/mac/release/libsubstance_ogl3_blend.1.dylib'],

        #==============================
        # ANDROID
        #==============================
        android_defines = ['AZ_USE_SUBSTANCE', 'AIR_NO_DYNLOAD'],

        #==============================
        # IOS
        #==============================
        ios_defines = ['AZ_USE_SUBSTANCE', 'AIR_NO_DYNLOAD'],
    )

    bld.recurse(SUBFOLDERS)
