########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):


    bld.CryStandAlonePlugin(

        # Settings
        target              = 'ProceduralMaterialEditorPlugin',
        vs_filter           = 'Sandbox/Plugins',
        file_list           = 'proceduralmaterialeditorplugin.waf_files',
        platforms           = ['win', 'darwin', 'linux'],
        exclude_monolithic  = True,
        client_only         = True,
    
        use                 = ['EditorCommon','EditorCore'],
        features            = 'qt5',

        # Common
        includes            = ['.',
                               bld.Path('Code/CryEngine/CryCommon'),
                               bld.Path('Code/Sandbox/Editor'),
                               bld.Path('Code/Sandbox/Editor/Include'),
                               bld.Path('Gems/Substance/Code/Include'),
                               bld.Path('Gems/Substance/External/6.0.0/include') ],

        uselib              = ['QT5CORE',
                               'QT5GUI',
                               'QT5WIDGETS',
                               'QTANGLE'],

        defines             = ['QT_NO_DEBUG',
                               'AZ_USE_SUBSTANCE',
                               'QT_DLL',
                               'QT_NO_EMIT',
                               'EDITOR_COMMON_IMPORTS'],

        win_x64_clang_cxxflags = ['-Wno-ignored-pragmas'],
        linux_rpath            = ['$ORIGIN/..'],
        msvc_cxxflags          = ['/wd4251'],

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['proceduralmaterialeditorplugin_test.waf_files'],
    )


