
def build(bld):
    bld.DefineGem(
        # General
        includes                = [
                                    'Include',
                                    bld.Path('Code/CryEngine/CryCommon'),
                                    bld.Path('Gems/LmbrCentral'),
                                  ],
        use                     = ['AzGameFramework'],
        disable_pch             = True,
        file_list               = ['ballgames.waf_files'],

        # Platform Roots
        platform_roots          = [bld.PlatformRoot('Platform', export_includes=False)],

        # Testing
        test_all_file_list      = ['ballgames_tests.waf_files'],

        # Add additional custom build options here
        # ...
    )
